2025-03-20 23:35:49,040 - ERROR - Ошибка в строке 0: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $3: Timestamp('2024-04-22 15:30:00-1700', tz... (Cannot subtract tz-naive and tz-aware datetime-like objects.)
[SQL: INSERT INTO reu_bot.products (section, product_name, date_time, id_school, location, url_scheme, id_conference) VALUES ($1::VARCHAR, $2::VARCHAR, $3::TIMESTAMP WITHOUT TIME ZONE, $4::INTEGER, $5::VARCHAR, $6::VARCHAR, $7::INTEGER) RETURNING reu_bot.products.id]
[parameters: ('Бизнес-проекты на английском языке', 'BUSINESS PLAN OPENING A STORE COSMETICS «PERFECTION» БИЗНЕС-ПЛАН ОТКРЫТИЕ МАГАЗИНА КОСМЕТИКИ “СОВЕРШЕНСТВО”', Timestamp('2024-04-22 15:30:00-1700', tz='UTC-17:00'), 1, '2.0', None, None)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2025-03-20 23:35:49,041 - CRITICAL - Критическая ошибка: name 'SQLAlchemyError' is not defined
2025-03-20 23:36:29,880 - ERROR - Ошибка в строке 0: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $3: Timestamp('2024-04-22 15:30:00-1700', tz... (Cannot subtract tz-naive and tz-aware datetime-like objects.)
[SQL: INSERT INTO reu_bot.products (section, product_name, date_time, id_school, location, url_scheme, id_conference) VALUES ($1::VARCHAR, $2::VARCHAR, $3::TIMESTAMP WITHOUT TIME ZONE, $4::INTEGER, $5::VARCHAR, $6::VARCHAR, $7::INTEGER) RETURNING reu_bot.products.id]
[parameters: ('Бизнес-проекты на английском языке', 'BUSINESS PLAN OPENING A STORE COSMETICS «PERFECTION» БИЗНЕС-ПЛАН ОТКРЫТИЕ МАГАЗИНА КОСМЕТИКИ “СОВЕРШЕНСТВО”', Timestamp('2024-04-22 15:30:00-1700', tz='UTC-17:00'), 1, '2.0', None, None)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2025-03-20 23:36:29,881 - ERROR - Ошибка базы данных: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $3: Timestamp('2024-04-22 15:30:00-1700', tz... (Cannot subtract tz-naive and tz-aware datetime-like objects.)
[SQL: INSERT INTO reu_bot.products (section, product_name, date_time, id_school, location, url_scheme, id_conference) VALUES ($1::VARCHAR, $2::VARCHAR, $3::TIMESTAMP WITHOUT TIME ZONE, $4::INTEGER, $5::VARCHAR, $6::VARCHAR, $7::INTEGER) RETURNING reu_bot.products.id]
[parameters: ('Бизнес-проекты на английском языке', 'BUSINESS PLAN OPENING A STORE COSMETICS «PERFECTION» БИЗНЕС-ПЛАН ОТКРЫТИЕ МАГАЗИНА КОСМЕТИКИ “СОВЕРШЕНСТВО”', Timestamp('2024-04-22 15:30:00-1700', tz='UTC-17:00'), 1, '2.0', None, None)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2025-03-20 23:36:29,881 - CRITICAL - Критическая ошибка: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $3: Timestamp('2024-04-22 15:30:00-1700', tz... (Cannot subtract tz-naive and tz-aware datetime-like objects.)
[SQL: INSERT INTO reu_bot.products (section, product_name, date_time, id_school, location, url_scheme, id_conference) VALUES ($1::VARCHAR, $2::VARCHAR, $3::TIMESTAMP WITHOUT TIME ZONE, $4::INTEGER, $5::VARCHAR, $6::VARCHAR, $7::INTEGER) RETURNING reu_bot.products.id]
[parameters: ('Бизнес-проекты на английском языке', 'BUSINESS PLAN OPENING A STORE COSMETICS «PERFECTION» БИЗНЕС-ПЛАН ОТКРЫТИЕ МАГАЗИНА КОСМЕТИКИ “СОВЕРШЕНСТВО”', Timestamp('2024-04-22 15:30:00-1700', tz='UTC-17:00'), 1, '2.0', None, None)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
2025-03-20 23:37:00,204 - ERROR - Ошибка в строке 0: name 'insert' is not defined
2025-03-20 23:37:00,204 - ERROR - Общая ошибка: name 'insert' is not defined
2025-03-20 23:37:00,205 - CRITICAL - Критическая ошибка: name 'insert' is not defined
2025-03-21 00:05:39,870 - ERROR - Ошибка в строке 0: 'AsyncSession' object has no attribute 'query'
2025-03-21 00:05:39,871 - ERROR - Общая ошибка: 'AsyncSession' object has no attribute 'query'
2025-03-21 00:05:39,871 - CRITICAL - Критическая ошибка: 'AsyncSession' object has no attribute 'query'
2025-03-21 00:06:42,869 - ERROR - Ошибка в строке 0: module 'sqlalchemy' has no attribute 'query'
2025-03-21 00:06:42,870 - ERROR - Общая ошибка: module 'sqlalchemy' has no attribute 'query'
2025-03-21 00:06:42,870 - CRITICAL - Критическая ошибка: module 'sqlalchemy' has no attribute 'query'
2025-03-21 00:07:26,064 - ERROR - Ошибка в строке 0: 'module' object is not callable
2025-03-21 00:07:26,065 - ERROR - Общая ошибка: 'module' object is not callable
2025-03-21 00:07:26,065 - CRITICAL - Критическая ошибка: 'module' object is not callable
2025-03-24 20:47:13,757 - ERROR - Ошибка: Worksheet named 'Конференции' not found
2025-03-24 20:47:13,757 - CRITICAL - Критическая ошибка: Worksheet named 'Конференции' not found
2025-03-24 20:48:05,152 - ERROR - Ошибка: Worksheet named 'Конференции' not found
2025-03-24 20:48:05,152 - CRITICAL - Критическая ошибка: Worksheet named 'Конференции' not found
2025-03-24 20:48:49,624 - ERROR - Ошибка: Worksheet named 'Конференции' not found
2025-03-24 20:48:49,640 - CRITICAL - Критическая ошибка: Worksheet named 'Конференции' not found
2025-03-24 20:48:55,810 - ERROR - Ошибка: name 'Conference' is not defined
2025-03-24 20:48:55,810 - CRITICAL - Критическая ошибка: name 'Conference' is not defined
